export default{
	mealarr1:function(){
		let arr1=[
			{
				meal:'中餐',
				tm_beg:11*3600,
				tm_end:7
			},
			{
				meal:'晚餐',
				tm_beg:15*3600,
				tm_end:6
			},
			
		];
		return arr1;
	},
	mealarr2:function(){
		let arr2=[
			{
				pt:'鱼香肉丝',
				imgurl:'one.png',
				rem:'本菜肉质爽滑，味道鲜香麻辣，适合各类人群食用。',
				order_by:0,
			},
			{
				pt:'青菜',
				imgurl:'one.png',
				rem:'青菜，又称胶菜、瓢儿菜、瓢儿白、油菜（中国东北某些地区）、油白菜等',
				order_by:1,
			},
			{
				pt:'排骨汤',
				imgurl:'one.png',
				rem:'排骨汤排骨汤，是用猪、牛、羊等动物剔肉后剩下的肋骨和脊椎骨制作的一道家常汤品。',
				order_by:2,
			},
			{
				pt:'茄子',
				imgurl:'one.png',
				rem:'茄科茄属植物。茄直立分枝草本至亚灌木，高可达1米，小枝，小枝多为紫色',
				order_by:3,
			},
			{
				pt:'土豆',
				imgurl:'one.png',
				rem:'土豆是重要的粮食、蔬菜作物,富含淀粉、胶、蛋白质、钾、柠檬酸、维生素和食物纤维。',
				order_by:4,
			},
			{
				pt:'炒面',
				imgurl:'one.png',
				rem:'一种是炒面条，另一种是炒面粉。炒面条是以面条、鸡蛋或肉为主要食材的面食。',
				order_by:5,
			},
			{
				pt:'兰州拉面',
				imgurl:'one.png',
				rem:'兰州拉面，是甘肃省兰州市的特色美食，是一种食品名称，原名兰州牛肉面，始于清朝嘉庆年间（1799年）',
				order_by:6,
			},
			{
				pt:'牛排',
				imgurl:'one.png',
				rem:'牛排，或称牛扒，是片状的牛肉，是西餐中常见的食物之一。',
				order_by:7,
			},
			{
				pt:'大黄鱼',
				imgurl:'one.png',
				rem:'大黄鱼在国内是出了名的高档海鲜，野生的大黄鱼更是可遇不可求，小的按斤卖，大的按条卖，定价数千元至上万元不等。',
				order_by:8,
			},
			{
				pt:'小黄鱼',
				imgurl:'one.png',
				rem:'小黄鱼又名小黄花鱼,脊椎动物,鱼纲,石首鱼科,',
				order_by:9,
			},
			{
				pt:'鲈鱼',
				imgurl:'one.png',
				rem:'鲈鱼一般指花鲈。',
				order_by:10,
			},
			{
				pt:'北京烤鸭',
				imgurl:'one.png',
				rem:'北京烤鸭被誉为世界珍味，它已有几百年的历史。制作烤鸭，要用北京多年驯化育养的一种特有的北京填鸭。',
				order_by:11,
			},
			{
				pt:'黄瓜',
				imgurl:'one.png',
				rem:'黄瓜含葡萄糖、鼠李糖、半孔糖、甘露糖、木糖、果糖',
				order_by:12,
			},
			{
				pt:'五香肉',
				imgurl:'one.png',
				rem:'五香猪肉是一道色香味俱全的传统名肴',
				order_by:13,
			},
			{
				pt:'糖醋排骨',
				imgurl:'one.png',
				rem:'中国名菜家常菜',
				order_by:14,
			},
			{
				pt:'红烧肉',
				imgurl:'one.png',
				rem:'一道著名的大众菜肴，各大菜系都有自己特色的红烧肉。',
				order_by:15,
			},
			{
				pt:'羊肉',
				imgurl:'one.png',
				rem:'羊肉是一种常见的食材',
				order_by:16,
			},
			{
				pt:'萝卜',
				imgurl:'one.png',
				rem:'中国名菜家常菜',
				order_by:17,
			},
			{
				pt:'炒大白菜',
				imgurl:'one.png',
				rem:'炒大白菜一般指炒白菜。 炒白菜是一道菜品，以白菜为主料。',
				order_by:18,
			},
			{
				pt:'酸辣土豆丝',
				imgurl:'one.png',
				rem:'以土豆为主材的美食中，最著名的要数酸辣土豆丝了',
				order_by:19,
			},
			{
				pt:'毛豆',
				imgurl:'one.png',
				rem:'毛豆是一种常见的食材',
				order_by:20,
			},
			{
				pt:'大排面',
				imgurl:'one.png',
				rem:'大排，生菜，青椒，红椒调料大排，熟猪油（或芝麻油），面砂糖。',
				order_by:21,
			},
			{
				pt:'干锅土豆',
				imgurl:'one.png',
				rem:'香辣干锅土豆 “干锅发源于四川绵阳,属于川北帮川菜,发扬光大于绵阳',
				order_by:22,
			},
			{
				pt:'芥菜',
				imgurl:'one.png',
				rem:'誉为[长寿菜],皆因它能清热解毒,对身体有益,荠菜耐寒强',
				order_by:23,
			},
			{
				pt:'炒牛里脊',
				imgurl:'one.png',
				rem:'炒牛里脊是一道美食，主要食材是牛里脊。',
				order_by:24,
			},
			{
				pt:'花菜',
				imgurl:'one.png',
				rem:'花菜又叫菜花、花椰菜。',
				order_by:25,
			},
			{
				pt:'砂锅',
				imgurl:'one.png',
				rem:'砂锅白菜炖豆腐,砂锅豆腐,三鲜砂锅,香辣砂锅豆腐,鸡丝砂锅土豆粉,香菇鸡砂锅等',
				order_by:26,
			},
			{
				pt:'麻辣豆腐',
				imgurl:'one.png',
				rem:'四川省传统名菜',
				order_by:27,
			},
			{
				pt:'韭菜炒蛋',
				imgurl:'one.png',
				rem:'韭菜炒鸡蛋',
				order_by:28,
			},
			{
				pt:'水饺',
				imgurl:'one.png',
				rem:'问世间情为何物,不过一碗酸汤水饺',
				order_by:29,
			},
			{
				pt:'可乐鸡翅',
				imgurl:'one.png',
				rem:'以鸡翅和可乐为主料制作而成。味道鲜美，色泽艳丽，鸡翅嫩滑，咸甜适中，又保留了可乐的香气',
				order_by:30,
			},
			{
				pt:'扬州炒饭',
				imgurl:'one.png',
				rem:'扬州炒饭又名扬州蛋炒饭',
				order_by:31,
			},
			{
				pt:'红烧排骨',
				imgurl:'one.png',
				rem:'红烧排骨是道很受欢迎的家常菜，不论是色、香、味都极具诱惑力',
				order_by:32,
			},
			{
				pt:'牛舌',
				imgurl:'one.png',
				rem:'牛舌含有酸、镁、钙、铁、锌等营养成分。',
				order_by:33,
			},
			{
				pt:'大盘鸡',
				imgurl:'one.png',
				rem:'新疆大盘鸡，又名沙湾大盘鸡、辣子炒鸡',
				order_by:34,
			},
			{
				pt:'宫爆鸡丁',
				imgurl:'one.png',
				rem:'是一道闻名中外的特色传统名菜，在鲁菜、川菜、贵州菜中都有收录',
				order_by:35,
			},
		];
		return arr2
	},
	mealarr3:function(){
		let arr3=[
			{
				pt:'鱼香肉丝',
				meal:'中餐',
				dt:'2022-05-16',
			},
			{
				pt:'青菜',
				meal:'中餐',
				dt:'2022-05-16',
				
			},
			{
				pt:'排骨汤',
				meal:'晚餐',
				dt:'2022-05-16',
			},
			{
				pt:'茄子',
				meal:'中餐',
				dt:'2022-05-16',
			},
			{
				pt:'茄子',
				meal:'中餐',
				dt:'2022-05-17',
			},
			{
				pt:'兰州拉面',
				meal:'中餐',
				dt:'2022-05-17',
			},
			{
				pt:'鲈鱼',
				meal:'中餐',
				dt:'2022-05-17',
			},
			{
				pt:'土豆',
				meal:'中餐',
				dt:'2022-05-17',
			},
			{
				pt:'土豆',
				meal:'晚餐',
				dt:'2022-05-17',
			},
			{
				pt:'牛排',
				meal:'晚餐',
				dt:'2022-05-17',
			},
			{
				pt:'炒面',
				meal:'中餐',
				dt:'2022-05-18',
			},
			{
				pt:'鲈鱼',
				meal:'中餐',
				dt:'2022-05-18',
			},
			{
				pt:'兰州拉面',
				meal:'晚餐',
				dt:'2022-05-18',
			},
			{
				pt:'炒面',
				meal:'晚餐',
				dt:'2022-05-18',
			},
			{
				pt:'鲈鱼',
				meal:'晚餐',
				dt:'2022-05-18',
			},
			{
				pt:'大黄鱼',
				meal:'晚餐',
				dt:'2022-05-18',
			},
			{
				pt:'牛排',
				meal:'中餐',
				dt:'2022-05-19',
			},
			{
				pt:'大黄鱼',
				meal:'晚餐',
				dt:'2022-05-19',
			},
			{
				pt:'小黄鱼',
				meal:'晚餐',
				dt:'2022-05-19',
			},
			{
				pt:'鲈鱼',
				meal:'晚餐',
				dt:'2022-05-20',
			},
			{
				pt:'鲈鱼',
				meal:'中餐',
				dt:'2022-05-20',
			},
			{
				pt:'大黄鱼',
				meal:'晚餐',
				dt:'2022-05-20',
			},
			{
				pt:'北京烤鸭',
				meal:'晚餐',
				dt:'2022-05-21',
			},
			{
				pt:'大黄鱼',
				meal:'中餐',
				dt:'2022-05-21',
			},
			{
				pt:'五香肉',
				meal:'中餐',
				dt:'2022-05-21',
			},
			{
				pt:'黄瓜',
				meal:'中餐',
				dt:'2022-05-22',
			},
			{
				pt:'五香肉',
				meal:'晚餐',
				dt:'2022-05-22',
			},
			{
				pt:'五香肉',
				meal:'中餐',
				dt:'2022-05-23',
			},
			{
				pt:'黄瓜',
				meal:'中餐',
				dt:'2022-05-23',
			},
			{
				pt:'五香肉',
				meal:'晚餐',
				dt:'2022-05-23',
			},
			{
				pt:'炒面',
				meal:'中餐',
				dt:'2022-05-24',
			},
			{
				pt:'兰州拉面',
				meal:'晚餐',
				dt:'2022-05-24',
			},
			{
				pt:'牛排',
				meal:'中餐',
				dt:'2022-05-24',
			},
		];
		return arr3
    },
mealarr4:function(){
		let arr4=[
			{
				pt:'扬州炒饭',
				meal:'中餐',
				wk:[0,6],
				beg_incl:'2022-05-16',
				end_excl:'2022-05-22',
			},
			{
				pt:'红烧排骨',
				meal:'晚餐',
				wk:[1,3],
				beg_incl:'2022-05-16',
				end_excl:'2022-05-22',
				
			},
			{
				pt:'排骨汤',
				meal:'晚餐',
				wk:[2,4],
				beg_incl:'2022-05-16',
				end_excl:'2022-05-22',
			},
			{
				pt:'茄子',
				meal:'中餐',
				wk:[2,5],
				beg_incl:'2022-05-17',
				end_excl:'2022-05-23',
			},
			{
				pt:'土豆',
				meal:'中餐',
				wk:[2,6],
				beg_incl:'2022-05-17',
				end_excl:'2022-05-23',
			},
			{
				pt:'牛舌',
				meal:'晚餐',
				wk:[5,6],
				beg_incl:'2022-05-18',
				end_excl:'2022-05-24',
			},
			{
				pt:'大盘鸡',
				meal:'晚餐',
				wk:[2,4],
				beg_incl:'2022-05-19',
				end_excl:'2022-05-25',
			},
			{
				pt:'宫爆鸡丁',
				meal:'中餐',
				wk:[1,4],
				beg_incl:'2022-05-19',
				end_excl:'2022-05-25',
			},
			{
				pt:'芥菜',
				meal:'晚餐',
				wk:[0,3],
				beg_incl:'2022-05-19',
				end_excl:'2022-05-25',
			},
			{
				pt:'炒牛里脊',
				meal:'晚餐',
				wk:[0,6],
				beg_incl:'2022-05-20',
				end_excl:'2022-05-26',
			},
			{
				pt:'花菜',
				meal:'晚餐',
				wk:[5,6],
				beg_incl:'2022-05-20',
				end_excl:'2022-05-26',
			},
			{
				pt:'砂锅',
				meal:'晚餐',
				wk:[1,4],
				beg_incl:'2022-05-20',
				end_excl:'2022-05-26',
			},
			{
				pt:'麻辣豆腐',
				meal:'中餐',
				wk:[1,6],
				beg_incl:'2022-05-21',
				end_excl:'2022-05-27',
			},
			{
				pt:'韭菜炒蛋',
				meal:'中餐',
				wk:[3,6],
				beg_incl:'2022-05-21',
				end_excl:'2022-05-27',
			},
		];
		return arr4;
	},
	
	mealarr5:function(){
			let arr5=[
				{
					pt:'大排面',
					meal:'中餐',
					beg_incl:'2022-04-01',
					end_excl:'2022-06-30',
				},
				{
					pt:'干锅土豆',
					meal:'中餐',
					beg_incl:'2022-04-01',
					end_excl:'2022-06-30',
					
				},
				{
					pt:'排骨汤',  //相同项
					meal:'晚餐',
					beg_incl:'2022-04-01',
					end_excl:'2022-06-30',
				},
				{
					pt:'炒牛里脊',
					meal:'晚餐',
					beg_incl:'2022-04-01',
					end_excl:'2022-06-30',
				},
				{
					pt:'花菜',
					meal:'晚餐',
					beg_incl:'2022-04-01',
					end_excl:'2022-06-30',
				},
				{
					pt:'砂锅',
					meal:'中餐',
					beg_incl:'2022-04-01',
					end_excl:'2022-06-30',
				},
				{
					pt:'麻辣豆腐',
					meal:'晚餐',
					beg_incl:'2022-07-01',
					end_excl:'2022-09-30',
				},
				{
					pt:'韭菜炒蛋',
					meal:'中餐',
					beg_incl:'2022-07-01',
					end_excl:'2022-09-30',
				},
				{
					pt:'水饺',
					meal:'晚餐',
					beg_incl:'2022-07-01',
					end_excl:'2022-09-30',
				},
				{
					pt:'可乐鸡翅',
					meal:'晚餐',
					beg_incl:'2022-07-01',
					end_excl:'2022-09-30',
				},
			
			];
			return arr5;
		},
		
}